In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
np.mean(a)

5.0

In [4]:
a = a.reshape(3,3)

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.mean(a)

5.0

In [7]:
np.mean(a,axis = 0)

array([4., 5., 6.])

In [8]:
np.mean(a,axis=1)

array([2., 5., 8.])

In [21]:
a = np.array([1,2,3,5,6,7,8,9])
np.median(a)

5.5

In [22]:
b = np.array([[2,3,5],[2,6,5]])
b

array([[2, 3, 5],
       [2, 6, 5]])

In [23]:
np.median(b)

4.0

In [24]:
np.median(b,axis=1)

array([3., 5.])

In [25]:
np.median(b,axis=0)

array([2. , 4.5, 5. ])

In [28]:
a = np.array([0.01,3,4,5,6,7,18])
np.mean(a
       )

6.144285714285714

In [29]:
np.median(a)

5.0