In [1]:
import numpy as np

In [2]:
a = np.array([2,1,4,5,6,2,5,4,1,2,4,5,6,2,1,4,5,6,2])
a

array([2, 1, 4, 5, 6, 2, 5, 4, 1, 2, 4, 5, 6, 2, 1, 4, 5, 6, 2])

In [3]:
a1 = np.unique(a)

In [4]:
a1

array([1, 2, 4, 5, 6])

In [8]:
val,count= np.unique(a,return_counts = True)

In [10]:
count

array([3, 5, 4, 4, 3], dtype=int64)

In [11]:
val

array([1, 2, 4, 5, 6])

In [12]:
mode = np.argmax(count)
mode

1

In [14]:
print("mode of data is:",val[mode])

mode of data is: 2


In [15]:
x = np.array([3,4,5,6,7])
x_mean = np.mean(x)
x_mean

5.0

In [17]:
x_var = np.var(x)
x_var

2.0

In [18]:
x_std = np.std(x)
x_std

1.4142135623730951

In [19]:
np.amin(a)

1

In [20]:
np.amax(a)

6

In [21]:
b = np.array([2,3,5,4,8,9]).reshape(2,3)
b

array([[2, 3, 5],
       [4, 8, 9]])

In [22]:
np.amin(b)

2

In [24]:
np.amax(b)

9

In [25]:
np.amin(b,axis = 0)

array([2, 3, 5])

In [27]:
np.amin(b,axis=1)

array([2, 4])

In [28]:
np.amax(b,axis=1)

array([5, 9])

In [30]:
np.average(b)


5.166666666666667

In [31]:
np.mean(b)

5.166666666666667

In [32]:
c = np.array([4,5,6])
w = np.array([8,2,3])

In [34]:
np.average(c)


5.0

In [37]:
np.average(c,weights=w)

4.615384615384615