In [1]:
import numpy as np
a = np.random.randint(5,10,16).reshape(4,4)
a


array([[7, 6, 7, 7],
       [6, 8, 7, 9],
       [9, 6, 5, 7],
       [6, 6, 5, 6]])

In [12]:
np.delete(a,0,axis = 0)

array([[6, 8, 7, 9],
       [9, 6, 5, 7],
       [6, 6, 5, 6]])

In [13]:
np.delete(a,1,1)

array([[7, 7, 7],
       [6, 7, 9],
       [9, 5, 7],
       [6, 5, 6]])

In [14]:
np.delete(a,1,0)

array([[7, 6, 7, 7],
       [9, 6, 5, 7],
       [6, 6, 5, 6]])

In [15]:
a+10

array([[17, 16, 17, 17],
       [16, 18, 17, 19],
       [19, 16, 15, 17],
       [16, 16, 15, 16]])