In [2]:
import numpy as np
arr = np.empty([4,2], dtype = np.uint16)
arr

array([[ 9579, 23184],
       [46885, 19008],
       [31882, 54032],
       [ 8501, 29289]], dtype=uint16)

In [4]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [11]:
a[(0,0),(0,2)]

array([3, 9])

In [18]:
a[0:20,0:20:2]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45],
       [51, 57]])