In [1]:
import numpy as np

In [2]:
a = np.array([[2,5],[8,5]])

In [3]:
a

array([[2, 5],
       [8, 5]])

In [4]:
np.sort(a)

array([[2, 5],
       [5, 8]])

In [5]:
np.sort(a,axis=0)

array([[2, 5],
       [8, 5]])

In [6]:
np.sort(a,axis=1)

array([[2, 5],
       [5, 8]])

In [7]:
np.sort(a,axis=None)

array([2, 5, 5, 8])

In [8]:
a

array([[2, 5],
       [8, 5]])

In [9]:
a[0,1]

5

In [10]:
b = np.array([[5,6,7],[8,5,9]])
b

array([[5, 6, 7],
       [8, 5, 9]])

In [11]:
np.sort(b)

array([[5, 6, 7],
       [5, 8, 9]])

In [12]:
np.argsort(b)

array([[0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [13]:
c = np.random.randint(1,20,10).reshape(2,5)
c

array([[18, 10,  7,  2, 17],
       [ 1, 18, 14,  1,  1]])

In [14]:
np.argmax(c)

0

In [15]:
np.argmax(c,axis=0)

array([0, 1, 1, 0, 0], dtype=int64)

In [16]:
np.argmax(c,axis=1)

array([0, 1], dtype=int64)

In [17]:
np.argmin(c)

5

In [18]:
np.argmin(c,axis=0)

array([1, 0, 0, 1, 1], dtype=int64)

In [19]:
np.argmin(c,axis=1)

array([3, 0], dtype=int64)

In [20]:
arr = np.random.randint(10,60,45).reshape(3,3,5)
arr

array([[[19, 24, 18, 59, 15],
        [49, 28, 46, 24, 25],
        [38, 36, 45, 52, 29]],

       [[58, 19, 37, 16, 12],
        [59, 36, 43, 40, 34],
        [46, 50, 53, 24, 56]],

       [[45, 31, 52, 31, 59],
        [10, 38, 42, 27, 18],
        [55, 44, 29, 13, 19]]])

In [21]:
np.max(arr)

59

In [22]:
np.argmax(arr)


3

In [23]:
np.argmax(arr,axis=0)


array([[1, 2, 2, 0, 2],
       [1, 2, 0, 1, 1],
       [2, 1, 1, 0, 1]], dtype=int64)

In [24]:
np.argmax(arr,axis=1)

array([[1, 2, 1, 0, 2],
       [1, 2, 2, 1, 2],
       [2, 2, 0, 0, 0]], dtype=int64)

In [25]:
np.min(arr)

10

In [26]:
np.argmin(arr)

35

In [27]:
np.argmin(arr,axis=0)

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 2],
       [0, 0, 2, 2, 2]], dtype=int64)

In [28]:
np.argmin(arr,axis=1)

array([[0, 0, 0, 1, 0],
       [2, 0, 0, 0, 0],
       [1, 0, 2, 2, 1]], dtype=int64)

In [31]:
np.where(arr>51)

(array([0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 2, 0, 0, 2], dtype=int64),
 array([3, 3, 0, 0, 2, 4, 2, 4, 0], dtype=int64))

In [33]:
np.where(arr<15)

(array([1, 2, 2], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([4, 0, 3], dtype=int64))

In [35]:
np.where(arr==45)

(array([0, 2], dtype=int64),
 array([2, 0], dtype=int64),
 array([2, 0], dtype=int64))